name: Filter and Send Email Report

on:
 # schedule:
   # - cron: '0 4 * * *'  # UTC 04:00 = Türkiye saati 07:00
  workflow_dispatch:  # Manuel çalıştırma seçeneği

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Depoyu kontrol et
      - name: Checkout repository
        uses: actions/checkout@v3

      # Python ortamını kur
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Bağımlılıkları yükle
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install imaplib2 pandas beautifulsoup4

      # Scripti çalıştır
      - name: Run script
        env:
          IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python main.py
